version: '3.8'

services:
  postgres:
    image: postgres:17-alpine  # Change to postgres:17 when available
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beeshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Uncomment to mount custom configuration
      # - ./postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d beeshop"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  postgres-network: